image: gitpod/workspace-docker

tasks:
  - name: Start App
    init: |
      docker-compose build
    command: |
      docker-compose up

ports:
  - port: 4200
    onOpen: open-preview
  - port: 8080
    onOpen: open-preview
  - port: 8000
    onOpen: open-preview
  - port: 3306
    onOpen: ignore
  - port: 9092
    onOpen: ignore
  - port: 2181
    onOpen: ignore
