version: "3.9"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app          # Live bind mount
      - ~/.m2:/root/.m2         # Cache Maven dependencies
    environment:
      - SPRING_PROFILES_ACTIVE=dev
